// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Cpp_pCopula_cbkmCopula
NumericVector Cpp_pCopula_cbkmCopula(IntegerVector d_moins_J, IntegerVector J, NumericMatrix u, NumericMatrix boxes, double size_box, int m, NumericVector weights, Function vCopula_wrapper);
RcppExport SEXP _empCop_Cpp_pCopula_cbkmCopula(SEXP d_moins_JSEXP, SEXP JSEXP, SEXP uSEXP, SEXP boxesSEXP, SEXP size_boxSEXP, SEXP mSEXP, SEXP weightsSEXP, SEXP vCopula_wrapperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type d_moins_J(d_moins_JSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type J(JSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type boxes(boxesSEXP);
    Rcpp::traits::input_parameter< double >::type size_box(size_boxSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Function >::type vCopula_wrapper(vCopula_wrapperSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpp_pCopula_cbkmCopula(d_moins_J, J, u, boxes, size_box, m, weights, vCopula_wrapper));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_empCop_Cpp_pCopula_cbkmCopula", (DL_FUNC) &_empCop_Cpp_pCopula_cbkmCopula, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_empCop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
