# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_intersect <- function(x_min, x_max, y_min, y_max) {
    .Call(`_empCop_Cpp_intersect`, x_min, x_max, y_min, y_max)
}

Cpp_pCopula_cbkmCopula <- function(d_moins_J, J, u, boxes, size_box, m, weights, vCopula_wrapper) {
    .Call(`_empCop_Cpp_pCopula_cbkmCopula`, d_moins_J, J, u, boxes, size_box, m, weights, vCopula_wrapper)
}

